[workspace]
resolver = "3"

[workspace.dependencies]
serde_json = { version = "1.0.149", features = ["std"] }

[package]
name = "utoipa-scalar-warpper"
version = "0.1.0"
edition = "2024"
license = "APACHE OR MIT"

[features]
default = []
axum = ["dep:axum", "http", "maud/axum", "utoipa/axum_extras"]

[dependencies]
axum = { version = "0.8", default-features = false, optional = true }
http = { version = "1", optional = true }
maud = { version = "0.27" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { workspace = true }
utoipa = { version = "5.4.0" }

[dev-dependencies]
axum = { version = "0.8" }
tokio = { version = "1.49.0", features = ["full"] }
utoipa-axum = { version = "0.2.0" }
utoipa-scalar-warpper = { version = "0.1.0", path = ".", features = ["axum"] }

[build-dependencies]
serde_json = { workspace = true }
