[package]
name = "xtask"
version = { workspace = true }
edition = { workspace = true }
publish = false

[dependencies]
clap = { version = "4", features = ["derive"] }
serde_json = { workspace = true }

[[bin]]
name = "xtask"
path = "main.rs"
